import { Navbar } from "@/components/navbar"
import { roboto } from "@/fonts"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Justhome Template",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn([
          "bg-background grid min-h-dvh antialiased",
          roboto.className
        ])}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
