import { Navbar } from "@/components/navbar"
import { roboto } from "@/fonts"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Justhome Template",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn([
          "bg-background text-foreground grid min-h-dvh antialiased",
          roboto.className
        ])}
      >
        <div className="w-full bg-amber-300 p-0.5 text-center text-xs">
          This design is based on the project by{" "}
          <a
            href="https://www.figma.com/community/file/1363146757495909701"
            target="_blank"
          >
            @shawon3
          </a>
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
